# Generated by Django 4.2.1 on 2023-12-19 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_alter_customer_id_alter_feedback_id_alter_orders_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='mobile',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits long.', regex='^[0-9]{10}$')]),
        ),
    ]
