# Generated by Django 4.2.1 on 2023-12-19 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_orders_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits long.', regex='^[0-9]{10}$')]),
        ),
    ]
