# Generated by Django 5.0.1 on 2024-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_product_avaliblity_product_qunatity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorderlevel',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
